package com.example

data class AllahName(val id: Int, val arabic: String, val transliteration: String, val meaning: String)

val allahNamesList = listOf(
    AllahName(1, "الرحمن", "Ar-Rahman", "The Beneficent"),
    AllahName(2, "الرحيم", "Ar-Raheem", "The Merciful"),
    AllahName(3, "الملك", "Al-Malik", "The King / Sovereign"),
    AllahName(4, "القدوس", "Al-Quddus", "The Most Holy"),
    AllahName(5, "السلام", "As-Salam", "The Source of Peace"),
    AllahName(6, "المؤمن", "Al-Mu'min", "The Guarantor of Faith"),
    AllahName(7, "المهيمن", "Al-Muhaymin", "The Guardian"),
    AllahName(8, "العزيز", "Al-Aziz", "The Almighty"),
    AllahName(9, "الجبار", "Al-Jabbar", "The Compeller"),
    AllahName(10, "المتكبر", "Al-Mutakabbir", "The Supreme"),
    AllahName(11, "الخالق", "Al-Khaliq", "The Creator"),
    AllahName(12, "البارئ", "Al-Bari", "The Maker"),
    AllahName(13, "المصور", "Al-Musawwir", "The Fashioner of Forms"),
    AllahName(14, "الغفار", "Al-Ghaffar", "The Ever-Forgiving"),
    AllahName(15, "القهار", "Al-Qahhar", "The All-Compelling"),
    AllahName(16, "الوهاب", "Al-Wahhab", "The Bestower"),
    AllahName(17, "الرزاق", "Ar-Razzaq", "The Provider"),
    AllahName(18, "الفتاح", "Al-Fattah", "The Opener"),
    AllahName(19, "العليم", "Al-Alim", "The All-Knowing"),
    AllahName(20, "القابض", "Al-Qabid", "The Restrainer"),
    AllahName(21, "الباسط", "Al-Basit", "The Expander"),
    AllahName(22, "الخافض", "Al-Khafid", "The Abaser"),
    AllahName(23, "الرافع", "Ar-Rafi", "The Exalter"),
    AllahName(24, "المعز", "Al-Mu'izz", "The Giver of Honor"),
    AllahName(25, "المذل", "Al-Mudhill", "The Giver of Dishonor"),
    AllahName(26, "السميع", "As-Sami", "The All-Hearing"),
    AllahName(27, "البصير", "Al-Basir", "The All-Seeing"),
    AllahName(28, "الحكم", "Al-Hakam", "The Judge"),
    AllahName(29, "العدل", "Al-Adl", "The Just"),
    AllahName(30, "اللطيف", "Al-Latif", "The Subtle One"),
    AllahName(31, "الخبير", "Al-Khabir", "The Aware"),
    AllahName(32, "الحليم", "Al-Halim", "The Forbearing"),
    AllahName(33, "العظيم", "Al-Azim", "The Magnificent"),
    AllahName(34, "الغفور", "Al-Ghafur", "The Forgiver and Hider of Faults"),
    AllahName(35, "الشكور", "Ash-Shakur", "The Rewarder of Thankfulness"),
    AllahName(36, "العلى", "Al-Ali", "The Highest"),
    AllahName(37, "الكبير", "Al-Kabir", "The Greatest"),
    AllahName(38, "الحفيظ", "Al-Hafiz", "The Preserver"),
    AllahName(39, "المقيت", "Al-Muqit", "The Nourisher"),
    AllahName(40, "الحسيب", "Al-Hasib", "The Reckoner"),
    AllahName(41, "الجليل", "Al-Jalil", "The Majestic"),
    AllahName(42, "الكريم", "Al-Karim", "The Bountiful"),
    AllahName(43, "الرقيب", "Ar-Raqib", "The Watchful"),
    AllahName(44, "المجيب", "Al-Mujib", "The Responsive"),
    AllahName(45, "الواسع", "Al-Wasi", "The All-Encompassing"),
    AllahName(46, "الحكيم", "Al-Hakim", "The Wise"),
    AllahName(47, "الودود", "Al-Wadud", "The Loving"),
    AllahName(48, "المجيد", "Al-Majid", "The All-Glorious"),
    AllahName(49, "الباعث", "Al-Ba'ith", "The Resurrecter"),
    AllahName(50, "الشهيد", "Ash-Shahid", "The Witness"),
    AllahName(51, "الحق", "Al-Haqq", "The Truth"),
    AllahName(52, "الوكيل", "Al-Wakil", "The Trustee"),
    AllahName(53, "القوى", "Al-Qawiyy", "The Possessor of All Strength"),
    AllahName(54, "المتين", "Al-Matin", "The Forceful"),
    AllahName(55, "الولى", "Al-Waliyy", "The Governor"),
    AllahName(56, "الحميد", "Al-Hamid", "The Praised"),
    AllahName(57, "المحصى", "Al-Muhsi", "The Appraiser"),
    AllahName(58, "المبدئ", "Al-Mubdi", "The Originator"),
    AllahName(59, "المعيد", "Al-Mu'id", "The Restorer"),
    AllahName(60, "المحيى", "Al-Muhyi", "The Giver of Life"),
    AllahName(61, "المميت", "Al-Mumit", "The Taker of Life"),
    AllahName(62, "الحي", "Al-Hayy", "The Ever-Living"),
    AllahName(63, "القيوم", "Al-Qayyum", "The Self-Existing"),
    AllahName(64, "الواجد", "Al-Wajid", "The Finder"),
    AllahName(65, "الماجد", "Al-Majid2", "The Glorious"),
    AllahName(66, "الواحد", "Al-Wahid", "The Unique"),
    AllahName(67, "الاحد", "Al-Ahad", "The One"),
    AllahName(68, "الصمد", "As-Samad", "The Eternal"),
    AllahName(69, "القادر", "Al-Qadir", "The All-Powerful"),
    AllahName(70, "المقتدر", "Al-Muqtadir", "The Creator of All Power"),
    AllahName(71, "المقدم", "Al-Muqaddim", "The Expediter"),
    AllahName(72, "المؤخر", "Al-Mu'akhkhir", "The Delayer"),
    AllahName(73, "الأول", "Al-Awwal", "The First"),
    AllahName(74, "الأخر", "Al-Akhir", "The Last"),
    AllahName(75, "الظاهر", "Az-Zahir", "The Manifest"),
    AllahName(76, "الباطن", "Al-Batin", "The Hidden"),
    AllahName(77, "الوالي", "Al-Wali", "The Patron"),
    AllahName(78, "المتعالي", "Al-Muta'ali", "The Supremely Exalted"),
    AllahName(79, "البر", "Al-Barr", "The Good"),
    AllahName(80, "التواب", "At-Tawwab", "The Ever-Returning"),
    AllahName(81, "المنتقم", "Al-Muntaqim", "The Avenger"),
    AllahName(82, "العفو", "Al-Afuww", "The Pardoner"),
    AllahName(83, "الرؤوف", "Ar-Ra'uf", "The Kind"),
    AllahName(84, "مالك الملك", "Malik-ul-Mulk", "The Owner of all Sovereignty"),
    AllahName(85, "ذو الجلال والإكرام", "Dhul-Jalal-wal-Ikram", "The Lord of Majesty and Generosity"),
    AllahName(86, "المقسط", "Al-Muqsit", "The Equitable"),
    AllahName(87, "الجامع", "Al-Jami", "The Gatherer"),
    AllahName(88, "الغنى", "Al-Ghani", "The Self-Sufficient"),
    AllahName(89, "المغنى", "Al-Mughni", "The Enricher"),
    AllahName(90, "المانع", "Al-Mani", "The Withholder"),
    AllahName(91, "الضار", "Ad-Darr", "The Distresser"),
    AllahName(92, "النافع", "An-Nafi", "The Propitious"),
    AllahName(93, "النور", "An-Nur", "The Light"),
    AllahName(94, "الهادي", "Al-Hadi", "The Guide"),
    AllahName(95, "البديع", "Al-Badi", "The Incomparable"),
    AllahName(96, "الباقي", "Al-Baqi", "The Everlasting"),
    AllahName(97, "الوارث", "Al-Warith", "The Supreme Inheritor"),
    AllahName(98, "الرشيد", "Ar-Rashid", "The Guide to the Right Path"),
    AllahName(99, "الصبور", "As-Sabur", "The Patient")
)
